# Generated by Django 5.1 on 2024-08-25 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pilotlog', '0002_airfield_imagepic_limitrules_myquerybuild_pilot_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='aircraft_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pilotlog.aircraft'),
        ),
    ]
