# Generated by Django 5.1 on 2024-08-25 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pilotlog', '0003_alter_flight_aircraft_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='aircraft',
            name='engyype',
            field=models.IntegerField(default=0),
        ),
    ]
